[project]

name = "hammer"
version = "0.1.0"
authors = ["Yehuda Katz <wycats@gmail.com>"]

[[lib]]

name = "hammer"

[dependencies.hamcrest]

version = "0.5.0"
git = "https://github.com/carllerche/hamcrest-rust.git"
